name: "build"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v2
      - name: "deps"
        run: apk add openssl-dev openssl linux-headers make go git
      - name: "build"
        run: make
      - name: "install"
        run: make install
      - name: "certs"
        run: make certificates
      - name: "md4"
        working-directory: utils/hashes
        run: go run md4.go --password test
